name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    adkakdkald
  adlada

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: pnpm install
      - run: pnpm run
