name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: npm install -g pnpm

      - run: pnpm install
      - run: pnpm run
